# Generated by Django 4.1.7 on 2023-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='last_parse',
            field=models.BooleanField(default=True),
        ),
    ]
